### ISSUE TITLE
Incorrect display of categories

### ISSUE THREAD

**Issue by mschilling** [mschilling/bite-pwa#2]
The categories displayed in the list of orders (history, profile) show the incorrect emoji's (<=static images).

<img width="302" alt="screenshot 2017-02-02 20 07 43" src="https://cloud.githubusercontent.com/assets/7045335/22564144/acb9f9f4-e983-11e6-9ef9-69b49d3fe55c.png">

**Comment by jstrating** [comment]
Bite now supports Apple Emoji's based on categories correctly.
